/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package nvim_lsp_test_project;

public class App {
    private SomeInterface i = new SomeImpl();
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        new App().i.foo();
    }
}
